change cloud aql proxy

diff --git a/charts/keycloak/templates/deployment.yaml b/charts/keycloak/templates/deployment.yaml
--- a/charts/keycloak/templates/deployment.yaml
+++ b/charts/keycloak/templates/deployment.yaml
@@ -14,7 +14,17 @@ spec:
       labels:
         app: keycloak
     spec:
-      serviceAccountName: default
+      serviceAccountName: keycloak
+      initContainers:
+        - name: wait-for-cloudsql-proxy-config
+          image: busybox:1.36
+          command: ["/bin/sh","-c"]
+          args:
+            - |
+              if [ "{{ .Values.cloudsql.enabled }}" != "true" ]; then echo "cloudsql disabled - skip"; exit 0; fi
+              if [ -z "{{ .Values.cloudsql.instanceConnectionName }}" ]; then echo "ERROR: instanceConnectionName empty"; exit 1; fi
+              echo "Config looks OK";
+              exit 0
       containers:
         - name: keycloak
           image: quay.io/keycloak/keycloak:24.0.1
@@ -88,11 +98,13 @@ spec:
             limits:
               cpu: "1"
               memory: 1.5Gi
+        {{- if .Values.cloudsql.enabled }}
         - name: cloud-sql-proxy
-          image: "{{ .Values.cloudsql.image }}"
+          image: {{ .Values.cloudsql.image }}
           command:
             - /cloud_sql_proxy
-            - -instances={{ .Values.cloudsql.instanceConnectionName }}=tcp:5432
+            - -log_debug_stdout
+            - -instances={{ required "cloudsql.instanceConnectionName is required" .Values.cloudsql.instanceConnectionName }}=tcp:5432
           securityContext:
             runAsNonRoot: true
             runAsUser: 65534
@@ -103,3 +115,4 @@ spec:
             limits:
               cpu: 200m
               memory: 256Mi
+        {{- end }}
